# Local development dependencies including docs building, website upload, ASV benchmark
name: wvutils
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  # test dependencies
  - pytest>=7.0.0
  - pytest-cov
  - pytest-xdist>=2.2.0
  # - pytest-asyncio>=0.17
  - coverage

  # Required dependencies
  - boto3>=1.18.44
  - botocore>=1.21.44
  - cloudpickle>=2.0.0
  # - google-re2>=0.2.20210901
  # - lxml>=4.6.3
  # - numpy>=1.21.2
  # - pandas>=1.3.3
  # - pyarrow==7.0.0
  # - requests>=2.26.0
  # - s3fs>=0.4.2
  - python-rapidjson>=1.5
  - urllib3>=1.26.6

  # Local testing dependencies
  - moto

  # Code checks
  - black=22.10.0
  - flake8=6.0.0
  - isort>=5.2.1
  - mypy=1.0
