name: Build wvutils
description: Build wvutils
runs:
  using: composite
  steps:
    - name: Environment Detail
      run: |
        micromamba info
        micromamba list
      shell: bash -el {0}

    - name: Build WVUtils
      run: |
        python -m pip install -e . --no-build-isolation --no-index
      shell: bash -el {0}
